name: fl_erp
description: Admin Panel.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  expandable:
  responsive_builder:
  firebase_storage:
  firebase_core:
  firebase_auth:
  firebase_database:
  firebase_analytics:
  google_fonts:
  image_picker:
  font_awesome_flutter:
  auto_size_text:
  page_transition:
  geolocator: any
#  multiselect_dropdown: ^2.0.0+1
  flutter_colorpicker:
#  multiple_select: ^0.1.23
  month_year_picker:
  clipboard:
  http:
  timeago:
  url_launcher:
  build_runner:
  sign_in_with_apple:
  rxdart:
  google_sign_in:
  built_value:
  cached_network_image: ^3.2.3
  cloud_firestore:
  searchfield:
  month_picker_dialog: ^2.0.2
  file_picker: ^5.3.2

#  image_picker:
  image_picker_web:
  mime_type:
  universal_html:
  path:
  provider:
  permission_handler:
  path_provider:
  open_file: ^3.3.2
  chewie:
  video_player:
#  dio:
  lottie:
  syncfusion_flutter_pdfviewer:
  animated_custom_dropdown:
  country_pickers:
  country:
  archive:
  shared_preferences:
  excel: ^2.0.0-null-safety-3
  csv:
  number_to_words:
#  number_to_text_converter : ^1.0.4
  easy_image_viewer:
  pdf:
  printing: ^5.11.0
  flutter_excel:
  intl_phone_field:
  pie_chart:
  shimmer:
  intl: ^0.18.0
  html_editor_enhanced: ^2.5.1
  flutter_rounded_progress_bar: ^0.3.2
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/images/globeIconPDF.png
     - assets/images/hennaicon.jpg
     - assets/images/login.gif
     - assets/images/loading.gif
     - assets/HR Dashboard/
     - assets/recipt Items/
#     - images/a_dot_ham.jpeg
  