name: fl_erp
description: Admin Panel.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  expandable: ^4.1.4
  responsive_builder: ^0.3.0
  syncfusion_flutter_charts: ^20.1.52
  firebase_storage: ^10.2.3
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  firebase_database: ^9.0.2
  firebase_analytics:
  google_fonts: 2.0.0
  image_picker:
  font_awesome_flutter:
  auto_size_text:
  page_transition:
  geolocator: any
  searchable_dropdown: ^1.1.3
  multiselect_dropdown: ^2.0.0+1
  flutter_colorpicker: ^0.6.0
  multiple_select: ^0.1.23
  month_year_picker: ^0.1.0+1
  clipboard: ^0.1.3
  http:
  timeago:
  url_launcher:
  build_runner:
  sign_in_with_apple:
  rxdart:
  google_sign_in:
  serializer: ^0.8.2
  built_value:
  cached_network_image:
  cloud_firestore:
  searchfield: ^0.5.6
  charts_flutter: ^0.12.0
#  month_picker_dialog: ^0.4.0
  month_picker_dialog_2: ^0.5.5
  file_picker: ^4.5.1

#  image_picker:
  image_picker_web: ^2.0.3+1
  mime_type: ^1.0.0
  universal_html: ^2.0.8
  path: ^1.8.0
  provider: ^5.0.0
  permission_handler:
  path_provider: ^2.0.10
  open_file: ^3.2.1
  chewie: ^1.0.0
  video_player: ^2.1.10
  flutter_chat_ui:
  dio: ^4.0.6
  lottie:
  syncfusion_flutter_pdfviewer: ^20.1.52-beta
  animated_custom_dropdown:
  country_pickers: ^2.0.0
  country: ^2.0.1
  archive: ^3.1.6
  shared_preferences: 2.0.11
  excel: ^2.0.0-null-safety-3
  csv: ^5.0.1
  number_to_words: ^1.0.0
  number_to_text_converter: ^1.0.4
  easy_image_viewer: ^1.2.0
  pdf:
  printing:
  flutter_excel: ^1.0.1
  intl_phone_field: ^3.1.0
  pie_chart: ^5.3.2
  shimmer:
  intl:



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/images/Leadzicon.png
     - assets/images/hennaicon.jpg
     - assets/images/login.gif
     - assets/images/loading.gif
     - assets/HR Dashboard/
     - assets/recipt Items/
#     - images/a_dot_ham.jpeg
  